name: Auto Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: SSH_PASSWORD
    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.21.0
      - run: sudo apt install sshpass
      - run: npm install -g @angular/cli
      - run: npm i
      - run: ng config -g cli.warnings.versionMismatch false
      - run: ng build --prod --base-href /~vangriea/info7/
      - run: sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r `pwd`/dist/my-app/* vangriea@transit.iut2.univ-grenoble-alpes.fr:public_html/info7/
